spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_NAME:mydb}
    username: ${DATASOURCE_USERNAME:app_user}
    password: ${DATASOURCE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
file:
  upload-path: ${MEDIA_PATH:/some}
