spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: app_user
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false
server:
  port: 8080