create table catalog (
        id integer generated by default as identity,
        price numeric(10,2),
        name varchar(100),
        description varchar(255),
        primary key (id)
)

create table image (
       catalog_id integer,
       id integer generated by default as identity,
       is_primary boolean not null,
       url varchar(2048),
       primary key (id)
)

alter table if exists image
    add constraint FKbfubn7t6iy1js3ae4g4to3doq
    foreign key (catalog_id)
    references catalog_entity