create table catalog (
    id integer generated by default as identity,
    price numeric(10,2),
    primary_image integer,
    name varchar(15),
    description varchar(200),
    primary key (id)
);
create table image (
    catalog_id integer,
    id integer generated by default as identity,
    filepath varchar(255),
    name varchar(255),
    type varchar(255),
    primary key (id)
);

alter table if exists image
    add constraint FKeovfoenmg24d894wa2qkw1qe
    foreign key (catalog_id)
    references catalog