create table category (
     id integer generated by default as identity,
     name varchar(25) not null unique,
     primary key (id)
);

alter table catalog
    add column category_id int;

alter table catalog
    add constraint fk_catalog_category
    foreign key (category_id)
    references category (id)
